### ISSUE TITLE
Can I use lodash?

### ISSUE THREAD

**Issue by ducdev** [longtran-pops/auto-complete#3]
Hi @longtran-pops 
I know the requirements said that:

```
No other libraries or frameworks are allowed. Whatever you need, you will need to write them on your own.
```

I did not install anything new, the `package.json`'s dependencies are still the same, but I see `lodash` already exists inside`node_modules`. Just need to clarify that I can use it to save sometime or not.

If it's also prohibited, I will use my own solutions.

Thank you.

**Comment by longtran-pops** [comment]
Hi @ducdev,
`lodash` have been added by react itself. In order to see how you solve the problem, I would like you to use your own solution instead.

**Comment by ducdev** [comment]
Hi @longtran-pops I will make changes to my PR using my own solution then, thanks for your response.
